### ISSUE TITLE
为啥跑不起来呢？

### ISSUE THREAD

**Issue by 89ck** [jie123108/imgsmlr-server#2]
我费劲儿千辛万苦， 运行就报错，然后一步步的增加对应的module， 最后， 还是没跑起来。

**Comment by jie123108** [comment]
如果跑不起来, 你需要提供更多的信息, 包括出错信息. 方便定位问题.
我找了一台新电脑(mac), 新的python环境(py3.9), 是能一次性跑起来的. 
使用docker-compose启动数据库.
pip 安装依赖包(使用豆瓣的源).
启动服务. 都能正常.
